---
controller_applications: "{{ controller_applications_all + controller_applications_site1 }}"
controller_credential_input_sources: "{{ controller_credential_input_sources_all + controller_credential_input_sources_site1 }}"
controller_credential_types: "{{ controller_credential_types_all + controller_credential_types_site1 }}"
controller_credentials: "{{ controller_credentials_all + controller_credentials_site1 }}"
controller_execution_environments: "{{ controller_execution_environments_all + controller_execution_environments_site1 }}"
controller_groups: "{{ controller_groups_all + controller_groups_site1 }}"
controller_hosts: "{{ controller_hosts_all + controller_hosts_site1 }}"
controller_instance_groups: "{{ controller_instance_groups_all + controller_instance_groups_site1 }}"
controller_inventories: "{{ controller_inventories_all + controller_inventories_site1 }}"
controller_inventory_sources: "{{ controller_inventory_sources_all + controller_inventory_sources_site1 }}"
controller_templates: "{{ controller_templates_all + controller_templates_site1 }}"
controller_labels: "{{ controller_labels_all + controller_labels_site1 }}"
controller_notifications: "{{ controller_notifications_all + controller_notifications_site1 }}"
controller_organizations: "{{ controller_organizations_all + controller_organizations_site1 }}"
controller_projects: "{{ controller_projects_all + controller_projects_site1 }}"
controller_roles: "{{ controller_roles_all + controller_roles_site1 }}"
controller_schedules: "{{ controller_schedules_all + controller_schedules_site1 }}"
controller_settings: "{{ controller_settings_all | combine(controller_settings_site1, list_merge='append') }}"
controller_teams: "{{ controller_teams_all + controller_teams_site1 }}"
controller_user_accounts: "{{ controller_user_accounts_all + controller_user_accounts_site1 }}"
controller_workflows: "{{ controller_workflows_all + controller_workflows_site1 }}"
env: site1
controller_port: 8443
ah_port: 8444
eda_port: 8445
scm_branch: # when you want it to be default branch just set to ""
...
